# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ElmDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ElmDemo
pod 'MJExtension', '~> 3.0.10'

  target 'ElmDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
